---
version: "3.8"
services:
  transmission:
    container_name: transmission
    image: linuxserver/transmission:latest
    restart: unless-stopped
    environment:
      TZ: ${TZ}
      PUID: ${PUID}
      PGID: ${PGID}
    ports: 
      - "9091:9091/tcp"
      - "51413:51413/tcp"
      - "51413:51413/udp"
    volumes:
      - ${ROOT}/:/downloads
      - ${ROOT}/opt/transmission/config:/config
  jackett:
    container_name: jackett
    image: linuxserver/jackett:latest
    restart: unless-stopped
    environment:
      TZ: ${TZ}
      PUID: ${PUID}
      PGID: ${PGID}
      UMASK_SET: "022"
    ports: 
      - "9117:9117/tcp"
    volumes:
      - ${ROOT}/opt/jackett/config:/config
  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr:latest
    restart: unless-stopped
    environment:
      TZ: ${TZ}
      PUID: ${PUID}
      PGID: ${PGID}
      UMASK_SET: "002"
    ports: 
      - "8989:8989/tcp"
    volumes:
      - ${ROOT}/:/downloads
      - ${ROOT}/opt/sonarr/config:/config
  radarr:
    container_name: radarr
    image: linuxserver/radarr:latest
    restart: unless-stopped
    environment:
      TZ: ${TZ}
      PUID: ${PUID}
      PGID: ${PGID}
      UMASK_SET: "022"
    ports: 
      - "7878:7878/tcp"
    volumes:
      - ${ROOT}/:/downloads
      - ${ROOT}/opt/radarr/config:/config
  readarr:
    container_name: readarr
    image: linuxserver/readarr:develop
    restart: unless-stopped
    environment:
      TZ: ${TZ}
      PUID: ${PUID}
      PGID: ${PGID}
      UMASK_SET: "022"
    ports: 
      - "8787:8787/tcp"
    volumes:
      - ${ROOT}/:/downloads
      - ${ROOT}/opt/readarr/config:/config
  lidarr:
    container_name: lidarr
    image: linuxserver/lidarr:latest
    restart: unless-stopped
    environment:
      TZ: ${TZ}
      PUID: ${PUID}
      PGID: ${PGID}
      UMASK_SET: "022"
    ports: 
      - "8686:8686/tcp"
    volumes:
      - ${ROOT}/:/downloads
      - /mnt/ssd/lidarr/config:/config
  lazylibrarian:
    container_name: lazylibrarian
    image: linuxserver/lazylibrarian:latest
    restart: unless-stopped
    environment:
      TZ: ${TZ}
      PUID: ${PUID}
      PGID: ${PGID}
      UMASK_SET: "022"
      DOCKER_MODS: "linuxserver/mods:universal-calibre|linuxserver/mods:lazylibrarian-ffmpeg"
    ports: 
      - "5299:5299/tcp"
    volumes:
      - ${ROOT}/:/downloads
      - ${ROOT}/opt/lazylibrarian:/config
  nginx:
    container_name: nginx
    image: nginx:1.23.1
    restart: unless-stopped
    environment:
      NGINX_HOST: hp1.risp.in
      NGINX_PORT: 80
    ports: 
      - "10.10.10.17:80:80/tcp"
    volumes:
      - ${ROOT}/opt/nginx/nginx.conf:/etc/nginx/nginx.conf
  mysql:
    container_name: mysql
    image: mariadb:10.9
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: ${MYSQL_ROOT}
    ports: 
      - "3306:3306/tcp"
    volumes:
      - ${ROOT}/opt/mysql:/var/lib/mysql
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    restart: unless-stopped
    environment:
      WEBPASSWORD: ${PIHOLE_PASSWORD}
      TZ: ${TZ}
      PUID: ${PUID}
      PGID: ${PGID}
      DNS_BOGUS_PRIV: "true"
      DNS_FQDN_REQUIRED: "true"
      VIRTUAL_HOST: pihole.risp.in
    ports: 
      - "10.10.10.11:53:53/tcp"
      - "10.10.10.11:53:53/udp"
      - "10.10.10.11:80:80/tcp"  
    volumes:
      - ${ROOT}/opt/pihole/etc/pihole:/etc/pihole
      - ${ROOT}/opt/pihole/etc/dnsmasq.d:/etc/dnsmasq.d
  dns:
    container_name: dns
    image: mjkaye/bind9-alpine:latest
    restart: unless-stopped
    ports: 
      - "10.10.10.53:53:53/tcp"
      - "10.10.10.53:53:53/udp"
    volumes:
      - ${ROOT}/opt/bind/named.conf:/etc/bind/named.conf
      - ${ROOT}/opt/bind/risp.in.zone:/var/bind/risp.in.zone
      - ${ROOT}/opt/bind/10.10.10.in-addr.arpa.zone:/var/bind/10.10.10.in-addr.arpa.zone
      - ${ROOT}/opt/bind/8.168.192.in-addr.arpa.zone:/var/bind/8.168.192.in-addr.arpa.zone
      - ${ROOT}/opt/bind/9.168.192.in-addr.arpa.zone:/var/bind/9.168.192.in-addr.arpa.zone
      - ${ROOT}/opt/bind/11.168.192.in-addr.arpa.zone:/var/bind/11.168.192.in-addr.arpa.zone

